version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Host port : Container port
    environment:
      MONGO_URI: mongodb://db:27017/mydatabase
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: "npm run start" # Adjust if using other scripts

  db:
    image: mongo:5.0.6
    container_name: mongo_db
    ports:
      - "27017:27017" # MongoDB default port
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
